default_language_version:
    python: python3.12

repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: venv/bin/black -l 79 -t py312 .
        language: script
        types: [ python ]
        pass_filenames: false
      - id: flake8
        name: flake8
        entry: venv/bin/flake8
        language: script
        args: [ --jobs=4 ]

  # TODO: Раскомментировать, когда в mypy появится поддержка PEP-695
  #  - repo: https://github.com/pre-commit/mirrors-mypy
  #    rev: v1.8.0
  #    hooks:
  #      - id: mypy
  #        entry: mypy .
  #        pass_filenames: false

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-docstring-first
        stages:
          - commit
          - push
      - id: check-merge-conflict
        stages:
          - push
      - id: trailing-whitespace
        stages:
          - commit
          - push
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: \.svg$
