volumes:
  postgres_data:


services:
  app:
    tty: true
    build:
      context: .
    environment:
      SQLALCHEMY_WARN_20: 1
      PYTHONUNBUFFERED: 1
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    command: ["./start_api.sh"]

  postgres:
    image: postgres:14.6-alpine
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: trade_hub
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
