name: Docker Compose Workflow

on:
  workflow_dispatch:

jobs:
  docker-compose-app-up:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and run with docker compose
      run: |
        docker-compose build
        export POSTGRESQL_USER=${{ secrets.POSTGRESQL_USER }}
        export POSTGRESQL_HOST=${{ secrets.POSTGRESQL_HOST }}
        export POSTGRESQL_PORT=${{ secrets.POSTGRESQL_PORT }}
        export POSTGRESQL_PASSWORD=${{ secrets.POSTGRESQL_PASSWORD }}
        export POSTGRESQL_DATABASE=${{ secrets.POSTGRESQL_DATABASE }}
        docker-compose -f docker-compose.yaml up -d

    - name: Get container logs if unhealthy
      if: failure()
      run: docker-compose logs

    - name: Run App
      run: |
        echo "Container is up and app is running"
